[tool.poetry]
name = "ezmsg-blackrock"
version = "0.1.0"
description = "Blackrock Cerebus ecosystem interface for ezmsg"
authors = ["Griffin Milsap <griffin.milsap@jhuapl.edu>"]
readme = "README.md"
homepage = "https://github.com/griffinmilsap/ezmsg-blackrock"
packages = [
  { include = "ezmsg", from = "src" }
]


[tool.poetry.dependencies]
python = "^3.8"
ezmsg = "^3.3.3"
pycbsdk = "^0.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
